easy_admin:
    site_name: '<a href="/home"><img src="https://i.goopics.net/wbLRD.png" height="60" width="70"  /></a> Admin'
    formats:
        date: 'd/m/Y'
        number: '%0.1f'
    entities:
        Movie:
            class: App\Entity\Movie
            label: 'Films'
            list:
                title: "Liste des films"
                fields: [{ property: 'id', label: 'Id' }, { property: 'title', label: 'Titre' }, { property: 'year', label: 'Date de sortie' }, { property: 'image', type: 'image', label: 'Jaquette' }, { property: 'critics', label: 'Note' }, { property: 'actor', label: 'Acteurs' }, { property: 'genre', label: 'Genre' }, { property: 'synopsis', label: 'Synopsis' }]
            form:
                fields:
                    - { property: 'title', type: 'text', label: 'Titre' }
                    - { property: 'image', type: 'text', label: 'Image' }
                    - { property: 'year',  label: 'Année de production', type_options: { widget: 'single_text' }}
                    - { property: 'critics', label: 'Notes spectateurs' }
                    - { property: 'synopsis', label: 'Synopsis' }
                    - { property: 'director', label: 'Réalisateur', type: 'entity', type_options: { choice_label: 'identityDirector' } }
                    - { property: 'production', label: 'Production', type: 'entity', type_options: { choice_label: 'name' } }
                    - { property: 'actor', label: 'Acteurs', type: 'entity', type_options: { choice_label: 'identityActor', multiple: 'true' } }
                    - { property: 'genre', label: 'Genre', type: 'entity', type_options: { choice_label: 'type', multiple: 'true' } }
        Actor:
            class: App\Entity\Actor
            label: 'Acteurs'
            list:
                title: "Liste des acteurs"
                fields: [{ property: 'id', label: 'Id' }, { property: 'name', label: 'Nom' }, { property: 'firstname', label: 'Prénom' }, { property: 'picture', type: 'image', label: 'Image' },{ property: 'birthdate', label: 'Date de naissance' }]
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Nom' }
                    - { property: 'firstname', type: 'text', label: 'Prénom' }
                    - { property: 'birthdate', type: 'date', label: 'Date de naissance', type_options: { widget: 'single_text' } }
                    - { property: 'picture', type: 'text', label: 'Image' }
        Genre:
            class: App\Entity\Genre
            label: 'Genres'
            list:
                title: "Liste des genres"
                fields: [{ property: 'id', label: 'Id' }, { property: 'type', label: 'Genre' }]
            form:
                fields:
                    - { property: 'type', type: 'text', label: 'Genre' }
        Director:
            class: App\Entity\Director
            label: 'Réalisateurs'
            list:
                title: "Liste des réalisateurs"
                fields: [{ property: 'id', label: 'Id' }, { property: 'name', label: 'Nom' }, { property: 'firstname', label: 'Prénom' }]
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Nom' }
                    - { property: 'firstname', type: 'text', label: 'Prénom' }
        Production:
            class: App\Entity\Production
            label: 'Productions'
            list:
                title: "Liste des producteurs de films"
                fields: [{ property: 'id', label: 'Id' }, { property: 'name', label: 'Nom' }]
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Nom' }
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: "Liste des utilisateurs"
                fields: [{ property: 'id', label: 'Id' }, { property: 'email', label: 'Email' }, { property: 'password', label: 'Password' }, { property: 'roles', label: 'Role' }]
    design:
        brand_color: '#1ABC9C'
        menu:
            - { entity: 'Movie', icon: 'film'}
            - { entity: 'Actor', icon: 'users'}
            - { entity: 'Genre', icon: 'star'}
            - { entity: 'Director', icon: 'play'}
            - { entity: 'Production', icon: 'credit-card'}
            - { entity: 'User', icon: 'users'}