easy_admin:
    entities:
        Movie:
            class: App\Entity\Movie
            form:
                fields:
                    - { property: 'title', type: 'text', label: 'Titre' }
                    - { property: 'year', label: 'Année de production' }
                    - { property: 'critics', label: 'Critiques' }
                    - { property: 'synopsis', label: 'Synopsis' }
                    - { property: 'genre', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Movie' } }
        Actor:
            class: App\Entity\Actor
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Nom' }
                    - { property: 'firstname', type: 'text', label: 'Prénom' }
                    - { property: 'birthdate', type: 'datetime', label: 'Date de naissance' }
        Genre:
            class: App\Entity\Genre
            form:
                fields:
                    - { property: 'type', type: 'text', label: 'Genre' }
        Production:
            class: App\Entity\Production
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Nom' }

    design:
        brand_color: '#1ABC9C'
